var countryToRegionMap = new Map([
    ['Afghanistan', 'Asia'],
    ['Albania', 'Europe'],
    ['Algeria', 'Africa'],
    ['American Samoa', 'Oceania'],
    ['Andorra', 'Europe'],
    ['Angola', 'Africa'],
    ['Antigua and Barbuda', 'North America'],
    ['Argentina', 'South America'],
    ['Armenia', 'Asia'],
    ['Aruba', 'South America'],
    ['Australia', 'Oceania'],
    ['Austria', 'Europe'],
    ['Azerbaijan', 'Asia'],
    ['Bahrain', 'Asia'],
    ['Bangladesh', 'Asia'],
    ['Barbados', 'North America'],
    ['Belarus', 'Europe'],
    ['Belgium', 'Europe'],
    ['Belize', 'North America'],
    ['Benin', 'Africa'],
    ['Bermuda', 'North America'],
    ['Bhutan', 'Asia'],
    ['Bolivia', 'South America'],
    ['Bosnia and Herzegovina', 'Europe'],
    ['Botswana', 'Africa'],
    ['Brazil', 'South America'],
    ['British Virgin Islands', 'North America'],
    ['Brunei', 'Asia'],
    ['Bulgaria', 'Europe'],
    ['Burkina Faso', 'Africa'],
    ['Burundi', 'Africa'],
    ['Cambodia', 'Asia'],
    ['Cameroon', 'Africa'],
    ['Canada', 'North America'],
    ['Cayman Islands', 'North America'],
    ['Central African Republic', 'Africa'],
    ['Chad', 'Africa'],
    ['Chile', 'South America'],
    ['China', 'Asia'],
    ['Colombia', 'South America'],
    ['Comoros', 'Africa'],
    ['Democratic Republic of the Congo', 'Africa'],
    ['Congo', 'Africa'],
    ['Costa Rica', 'North America'],
    ["Cote d'Ivoire", 'Africa'],
    ['Croatia', 'Europe'],
    ['Cuba', 'North America'],
    ['Cyprus', 'Europe'],
    ['Czech Republic', 'Europe'],
    ['Denmark', 'Europe'],
    ['Djibouti', 'Africa'],
    ['Dominica', 'North America'],
    ['Dominican Republic', 'North America'],
    ['Ecuador', 'South America'],
    ['Egypt', 'Africa'],
    ['El Salvador', 'North America'],
    ['Guinea', 'Africa'],
    ['Eritrea', 'Africa'],
    ['Estonia', 'Europe'],
    ['Ethiopia', 'Africa'],
    ['Faroe Islands', 'Europe'],
    ['Fiji', 'Oceania'],
    ['Finland', 'Europe'],
    ['France', 'Europe'],
    ['French Polynesia', 'Oceania'],
    ['Gabon', 'Africa'],
    ['The Gambia', 'Africa'],
    ['Georgia', 'Europe'],
    ['Germany', 'Europe'],
    ['Ghana', 'Africa'],
    ['Gibraltar', 'Europe'],
    ['Greece', 'Europe'],
    ['Greenland', 'North America'],
    ['Grenada', 'North America'],
    ['Guam', 'Oceania'],
    ['Guatemala', 'North America'],
    ['Guinea Bissau', 'Africa'],
    ['Guyana', 'South America'],
    ['Haiti', 'North America'],
    ['Honduras', 'North America'],
    ['Hong Kong SAR, China', 'Asia'],
    ['Hungary', 'Europe'],
    ['Iceland', 'Europe'],
    ['India', 'Asia'],
    ['Indonesia', 'Asia'],
    ['Iran', 'Asia'],
    ['Iraq', 'Asia'],
    ['Ireland', 'Europe'],
    ['Isle of Man', 'Europe'],
    ['Israel', 'Asia'],
    ['Italy', 'Europe'],
    ['Jamaica', 'North America'],
    ['Japan', 'Asia'],
    ['Jordan', 'Asia'],
    ['Kazakhstan', 'Asia'],
    ['Kenya', 'Africa'],
    ['Kiribati', 'Oceania'],
    ['North Korea', 'Asia'],
    ['South Korea', 'Asia'],
    ['Kosovo', 'Europe'],
    ['Kuwait', 'Asia'],
    ['Kyrgyzstan', 'Asia'],
    ['Laos', 'Asia'],
    ['Latvia', 'Europe'],
    ['Lebanon', 'Asia'],
    ['Lesotho', 'Africa'],
    ['Liberia', 'Africa'],
    ['Libya', 'Africa'],
    ['Liechtenstein', 'Europe'],
    ['Lithuania', 'Europe'],
    ['Luxembourg', 'Europe'],
    ['Macao SAR, China', 'Asia'],
    ['Madagascar', 'Africa'],
    ['Malawi', 'Africa'],
    ['Malaysia', 'Asia'],
    ['Maldives', 'Asia'],
    ['Mali', 'Africa'],
    ['Malta', 'Europe'],
    ['Marshall Islands', 'Oceania'],
    ['Mauritania', 'Africa'],
    ['Mauritius', 'Africa'],
    ['Mexico', 'North America'],
    ['Micronesia', 'Oceania'],
    ['Moldova', 'Europe'],
    ['Monaco', 'Europe'],
    ['Mongolia', 'Asia'],
    ['Montenegro', 'Europe'],
    ['Morocco', 'Africa'],
    ['Mozambique', 'Africa'],
    ['Myanmar', 'Asia'],
    ['Namibia', 'Africa'],
    ['Nauru', 'Oceania'],
    ['Nepal', 'Asia'],
    ['Netherlands', 'Europe'],
    ['New Caledonia', 'Oceania'],
    ['New Zealand', 'Oceania'],
    ['Nicaragua', 'North America'],
    ['Niger', 'Africa'],
    ['Nigeria', 'Africa'],
    ['North Macedonia', 'Europe'],
    ['Northern Mariana Islands', 'Oceania'],
    ['Norway', 'Europe'],
    ['Oman', 'Asia'],
    ['Pakistan', 'Asia'],
    ['Palau', 'Oceania'],
    ['Panama', 'North America'],
    ['Papua New Guinea', 'Oceania'],
    ['Paraguay', 'South America'],
    ['Peru', 'South America'],
    ['Philippines', 'Asia'],
    ['Poland', 'Europe'],
    ['Portugal', 'Europe'],
    ['Puerto Rico', 'North America'],
    ['Qatar', 'Asia'],
    ['Romania', 'Europe'],
    ['Russia', 'Europe'],
    ['Rwanda', 'Africa'],
    ['Samoa', 'Oceania'],
    ['San Marino', 'Europe'],
    ['Sao Tome and Principe', 'Africa'],
    ['Saudi Arabia', 'Asia'],
    ['Senegal', 'Africa'],
    ['Serbia', 'Europe'],
    ['Seychelles', 'Africa'],
    ['Sierra Leone', 'Africa'],
    ['Singapore', 'Asia'],
    ['Slovakia', 'Europe'],
    ['Slovenia', 'Europe'],
    ['Solomon Islands', 'Oceania'],
    ['Somalia', 'Africa'],
    ['South Africa', 'Africa'],
    ['South Sudan', 'Africa'],
    ['Spain', 'Europe'],
    ['Sri Lanka', 'Asia'],
    ['St. Kitts and Nevis', 'North America'],
    ['St. Lucia', 'North America'],
    ['St. Martin (French part)', 'North America'],
    ['St. Vincent and the Grenadines', 'North America'],
    ['Western Sahara', 'Africa'],
    ['Sudan', 'Africa'],
    ['Suriname', 'South America'],
    ['Sweden', 'Europe'],
    ['Switzerland', 'Europe'],
    ['Syria', 'Asia'],
    ['Tajikistan', 'Asia'],
    ['Tanzania', 'Africa'],
    ['Thailand', 'Asia'],
    ['The Bahamas', 'North America'],
    ['Timor-Leste', 'Asia'],
    ['Togo', 'Africa'],
    ['Tonga', 'Oceania'],
    ['Trinidad and Tobago', 'South America'],
    ['Tunisia', 'Africa'],
    ['Turkey', 'Asia'],
    ['Turkmenistan', 'Asia'],
    ['Turks and Caicos Islands', 'North America'],
    ['Tuvalu', 'Oceania'],
    ['Uganda', 'Africa'],
    ['Ukraine', 'Europe'],
    ['United Arab Emirates', 'Asia'],
    ['United Kingdom', 'Europe'],
    ['United States', 'North America'],
    ['Uruguay', 'South America'],
    ['Uzbekistan', 'Asia'],
    ['Vanuatu', 'Oceania'],
    ['Venezuela', 'South America'],
    ['Vietnam', 'Asia'],
    ['Virgin Islands (U.S.)', 'North America'],
    ['West Bank and Gaza', 'Asia'],
    ['Yemen', 'Asia'],
    ['Zambia', 'Africa'],
    ['Zimbabwe', 'Africa']
]);